### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'elements')     at Object.<anonymous> (/usr/local/lib/node_modules/debundle/src/index.js:63:59)

### ISSUE THREAD

**Issue by Drjacky** [1egoman/debundler#30]
> * Using default AST location for browserify...
> * Reading bundle...
> * Using auto-discovered browserify entry point...
/usr/local/lib/node_modules/debundle/src/index.js:63
  config.entryPoint = ast.body[0].expression.arguments[2].elements[0].value;
                                                          ^

> TypeError: Cannot read properties of undefined (reading 'elements')
    at Object.<anonymous> (/usr/local/lib/node_modules/debundle/src/index.js:63:59)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47

Node.js v18.8.0

**Comment by laveshverma007** [comment]
Facing the same issue, any update on this?
